auto_system_proxy = true
[log]
level = "info"
output = "run.log"
max_size = "3MB"

[dns]
server = "https://dns.alidns.com/dns-query"

[geo]
update_interval = "72h"
ip_url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"
site_url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"

[routing]
rules = [
    { inbound_tags = [ "geo" ], outbound_tags = [ "proxy" ] },
    { include_hosts = [
        "geosite:category-ads-all",
    ], outbound_tags = [
        "block",
    ] },
    { outbound_tags = [
        "direct",
    ], include_hosts = [
        "private",
        "geoip:cn",
        "geosite:cn",
    ] },
    { outbound_tags = [
        "proxy",
    ] },
]

[[inbounds]]
tag = "entry"
protocol = "mixed"
listen = "127.0.0.1:1080"


[[outbounds]]
tag = "proxy"
protocol = "lite"
protocol_settings = { user = { id = "00000000000000000000000000000000" } }
transport = "websocket"
transport_settings = { only_httpupgrade = true, path = "/ws", host = "1.1.1.1" }
tls = { server_name = "1.1.1.1", cert_path = "cert.pem", cert_hash = "", insecure = false }
server = "1.1.1.1:443"

[[outbounds]]
tag = "direct"
dial_mode = "auto"
